Repository Codeit-FE3-Part3-team6-Taskify/Taskify, pull requests merged in 2024-03, with the labels that each got.

#11 ✨ feat : 로그인, 회원가입 input
  .eslintrc
  src/components/SignInput/PasswordInput.jsx
  src/components/SignInput/UserInformationInput.jsx
  src/features/axios.js
  src/features/user.js
  src/pages/signin.js
  src/styles/globals.css
  src/utils/validation.js
  tailwind.config.js
Labels: 공용 컴포넌트

#12 ✨ feat: 버튼 디폴트 컴포넌트 추가
  .eslintrc
  src/components/Buttons/CtaAdd/CtaAdd.jsx
  src/components/Buttons/CtaDefault/CtaDefault.jsx
  src/components/Buttons/CtaIcon/CtaIcon.jsx
  src/components/Buttons/DashboardDelete/DashboardDelete.jsx
  src/components/Buttons/DashboardListItem/DashboardListItem.jsx
  src/components/Buttons/PagenationArrow/PagenationArrow.jsx
  src/components/index.jsx
  src/pages/index.js
  src/styles/globals.css
  tailwind.config.js
Labels: 공용 컴포넌트

#14 💄 design: 공용 Header 컴포넌트, Avatar 컴포넌트 추가
  public/images/CombinedLogo.svg
  public/images/CombinedLogoWhite.svg
  public/images/index.js
  src/components/Avatar/Avatar.jsx
  src/components/Avatar/AvatarGroup.jsx
  src/components/Header/DashboardHeader.jsx
  src/components/Header/DefaultHeader.jsx
  tailwind.config.js
Labels: 공용 컴포넌트

#18 Feature 송상훈
  src/components/Sidebar/Sidebar.jsx
  src/styles/globals.css
  tailwind.config.js
Labels: 공용 컴포넌트

#22 ✨ Feat : 로그인/회원가입페이지 완성
  package-lock.json
  package.json
  src/components/Buttons/CtaDefault/CtaDefault.jsx
  src/components/Buttons/PaginationButton/PaginationButton.jsx
  src/components/SignLink/SignLink.jsx
  src/components/SignLogo/SignLogo.jsx
  src/features/store.js
  src/features/user.js
  src/features/userInfoSlice.js
  src/pages/_app.js
  src/pages/signin.js
  src/pages/signup.js
  src/utils/validation.js
  tailwind.config.js
Labels: 로그인/회원가입

#24 ✨ feat: 공통 모달 오픈 로직 추가, 알럿 모달 추가
  .eslintrc
  src/components/Buttons/CtaDefault/CtaDefault.jsx
  src/components/Buttons/PaginationButton/PaginationButton.jsx
  src/components/Modal/AlertModal/AlertModal.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/ModalContainer.jsx
  src/features/modalSlice.js
  src/features/store.js
  src/hooks/useModal.jsx
  src/hooks/useOutSideClick.jsx
  src/pages/_app.js
  src/pages/_document.js
  src/pages/index.js
  tailwind.config.js
Labels: 공용 컴포넌트, 모달

#25 메인 랜딩페이지 완성
  public/images/Landing1.png
  public/images/Landing2.png
  public/images/Landing3.png
  public/images/Landing4.png
  public/images/Landing5.png
  public/images/Landing6.png
  public/images/index.js
  src/components/Header/DashboardHeader.jsx
  src/components/Header/DefaultHeader.jsx
  src/components/LandingPage/LandingCard/LandingCard.jsx
  src/components/LandingPage/LandingFooter/LandingFooter.jsx
  src/components/SignInput/PasswordInput.jsx
  src/pages/_document.js
  src/pages/index.js
  src/pages/signup.js
  src/styles/globals.css
  src/utils/validation.js
Labels: 메인 랜딩페이지

#33 랜딩푸터 마진추가
  src/components/LandingPage/LandingFooter/LandingFooter.jsx
Labels: 메인 랜딩페이지

#38 로그인/회원가입 alert 모달추가
  src/features/user.js
  src/pages/signin.js
  src/pages/signup.js
Labels: 로그인/회원가입

#39 할일 생성 모달 완료
  .eslintrc
  package-lock.json
  package.json
  src/components/Dashboard/CreateTodoModal.jsx
  src/components/MyPage/MyPageContent/UpdatePassword.jsx
  src/components/MyPage/MyPageContent/UpdateProfile.jsx
  src/components/common/CustomDatePicker/CustomDatePicker.jsx
  src/components/common/FileUpload/FileUpload.jsx
  src/components/common/Modal/Modal.jsx
  src/components/common/Modal/ModalContainer.jsx
  src/components/common/SelectMenu/SelectMenu.jsx
  src/components/common/Tag/TagInput.jsx
  src/components/common/Tag/TagItem.jsx
  src/constants/colors.js
  src/features/axios.js
  src/pages/myPage.jsx
  src/pages/test.jsx
  src/utils/getRandomColorPair.js
Labels: 대시보드, 모달

#44 ✨feat : 대시보드 페이지 거의 완성
  public/images/DeleteIcon.jpg
  public/images/Edit.svg
  public/images/index.js
  src/components/Dashboard/DashboardCard/DashboardCard.jsx
  src/components/Dashboard/DashboardColumn/DashboardColumn.jsx
  src/components/Dashboard/DashboardColumnForm/DashboardColumnForm.jsx
  src/features/user.js
  src/features/userInfoSlice.js
  src/hooks/useDashboardInfo.jsx
  src/hooks/useDashboardList.jsx
  src/hooks/useUserGet.jsx
  src/pages/_app.jsx
  src/pages/_document.jsx
  src/pages/dashboard/[dashboardId].jsx
  src/pages/index.jsx
  src/pages/mydashboard.jsx
  src/pages/signin.jsx
  src/pages/signup.jsx
  tailwind.config.js
Labels: 대시보드

#52 ✨ Feat 카드 무한 스크롤 및 컬럼 생성 모달 연결
  src/components/Dashboard/DashboardCard/DashboardCard.jsx
  src/components/Dashboard/DashboardColumn/DashboardColumn.jsx
  src/components/common/Modal/CreateColumnModal/CreateColumnModal.jsx
  src/hooks/useDashboardCardGet.jsx
  src/hooks/useDashboardInfo.jsx
  src/pages/dashboard/[dashboardId].jsx
  src/pages/test.jsx
Labels: 대시보드

#53 ✨ 할 일 수정 모달 완성
  public/images/Ellipse.svg
  public/images/index.js
  src/components/Dashboard/TodoCard/CreateTodo.jsx
  src/components/Dashboard/TodoCard/UpdateTodo.jsx
  src/components/common/Avatar/AvatarGroup.jsx
  src/components/common/CustomDatePicker/CustomDatePicker.jsx
  src/components/common/DropdownMenu/DropdownMenu.jsx
  src/components/common/Header/DashboardHeader.jsx
  src/components/common/Modal/AlertModal/AlertModal.jsx
  src/components/common/Modal/Modal.jsx
  src/components/common/Modal/ModalContainer.jsx
  src/components/common/Modal/TodoModal/TodoModal.jsx
  src/components/common/SelectMenu/SelectMenu.jsx
  src/components/common/StatusTag/StatusTag.jsx
  src/components/common/Tag/TagInput.jsx
  src/features/axios.js
  src/pages/test.jsx
Labels: 대시보드, 모달

#57 ✨feat: 드래그 앤 드롭 기능 추가
  package-lock.json
  package.json
  src/components/Dashboard/DashboardColumn/DashboardColumn.jsx
  src/components/Dashboard/TodoCard/CreateTodo.jsx
  src/features/columnsSlice.js
  src/features/memberSlice.js
  src/features/store.js
  src/features/userInfoSlice.js
  src/hooks/useDashboardCardGet.jsx
  src/hooks/useRedirectWithAccessToken.jsx
  src/pages/dashboard/[dashboardId].jsx
  src/pages/index.jsx
  src/pages/signin.jsx
  src/pages/signup.jsx
  src/pages/test.jsx
Labels: 대시보드

#59 랜딩페이지 이미지 교체, 할일 카드 작업중
  public/images/Landing1.png
  public/images/Landing1.svg
  public/images/Landing2.png
  public/images/Landing2.svg
  public/images/Landing3.png
  public/images/Landing3.svg
  public/images/Landing4.png
  public/images/Landing4.svg
  public/images/Landing5.png
  public/images/Landing5.svg
  public/images/Landing6.png
  public/images/Landing6.svg
  public/images/index.js
  src/components/common/DropdownMenu/DropdownMenu.jsx
  src/components/common/Modal/CardModal/CardModal.jsx
  src/components/common/Modal/ModalContainer.jsx
  src/components/common/Modal/TodoModal/TodoModal.jsx
  src/components/common/SelectMenu/SelectMenu.jsx
  src/components/common/Tag/TagInput.jsx
  src/components/common/Tag/TagItem.jsx
  src/pages/myPage.jsx
  src/pages/test.jsx
Labels: 버그픽스, 모달

#61 feat:마이대시보드 수락,거절 기능 구현 완료
  src/components/MydashboardPage/DashboardList/DashboardList.jsx
  src/components/MydashboardPage/InvitedDashboard/InvitedDashboard.jsx
  src/features/invitationsDashboardListSlice.js
  src/features/store.js
  src/hooks/useGetInvitedDashboards.js
  src/pages/mydashboard.jsx
Labels: 공용 컴포넌트, 나의 대시보드

#62 ✨feat 할일 모달 기능 및 columnSlice 동작하도록 수정 등
  src/components/Dashboard/DashboardCard/DashboardCard.jsx
  src/components/Dashboard/DashboardColumn/DashboardColumn.jsx
  src/components/Dashboard/TodoCard/CreateTodo.jsx
  src/components/common/Modal/TodoModal/TodoModal.jsx
  src/components/common/SelectMenu/SelectMenu.jsx
  src/features/columnsSlice.js
  src/hooks/useDashboardCardGet.jsx
  src/hooks/useRedirectWithAccessToken.jsx
  src/pages/dashboard/[dashboardId].jsx
  src/pages/index.jsx
  src/pages/signin.jsx
  src/pages/signup.jsx
Labels: 대시보드

#63 🐛fix : 페이지 이동시 툴킷 오류 수정
  src/features/columnsSlice.js
  src/hooks/useDashboardInfo.jsx
Labels: 대시보드

#65 ♻️refactor : 일부 컴포넌트 화 및 컬럼아이디 고정 수정
  src/components/Dashboard/DashboardCardList/DashboardCardList.jsx
  src/components/Dashboard/DashboardColumn/DashboardColumn.jsx
  src/components/Dashboard/DashboardColumnHeader/DashboardColumnHeader.jsx
  src/components/Dashboard/DashboardHeaderButton/DashboardHeaderButton.jsx
  src/components/Dashboard/TodoCard/CreateTodo.jsx
  src/hooks/useDashboardInfo.jsx
  src/hooks/useDashboardUtilityFunctions.jsx
  src/hooks/useGetDashboardsSidebar.js
  src/pages/dashboard/[dashboardId].jsx
  src/pages/myPage.jsx
  src/pages/mydashboard.jsx
Labels: 대시보드

#66 ✨ : 할일 카드 모달 기능만 완성
  src/components/Dashboard/DashboardCard/DashboardCard.jsx
  src/components/common/Avatar/Avatar.jsx
  src/components/common/Avatar/AvatarGroup.jsx
  src/components/common/Header/DashboardHeader.jsx
  src/components/common/Modal/CardModal/CardModal.jsx
  src/components/common/PopupMenu/PopupMenu.jsx
  src/components/common/SelectMenu/SelectMenu.jsx
  src/pages/test.jsx
Labels: 대시보드, 모달

#71 feat : 할일 카드 수정 삭제 연결 및 렌더링 동작
  src/components/Dashboard/DashboardCard/DashboardCard.jsx
  src/components/Dashboard/DashboardCardList/DashboardCardList.jsx
  src/components/Dashboard/DashboardColumn/DashboardColumn.jsx
  src/components/Dashboard/DashboardHeaderButton/DashboardHeaderButton.jsx
  src/components/Dashboard/TodoCard/CreateTodo.jsx
  src/components/Dashboard/TodoCard/UpdateTodo.jsx
  src/components/common/DropdownMenu/DropdownMenu.jsx
  src/components/common/Modal/CardModal/CardModal.jsx
  src/components/common/Modal/TodoModal/TodoModal.jsx
  src/components/common/PopupMenu/PopupMenu.jsx
  src/components/common/SelectMenu/SelectMenu.jsx
  src/pages/dashboard/[dashboardId].jsx
  src/pages/dashboard/[dashboardId]/edit.jsx
  src/pages/myPage.jsx
Labels: 대시보드

#73 🐛 fix : 빌드 오류해결
  .eslintrc
  package-lock.json
  package.json
  public/images/index.js
  src/components/Dashboard/TodoCard/UpdateTodo.jsx
  src/components/DashboardEdit/EditContent/DashboardEditPanel.jsx
  src/components/DashboardEdit/EditContent/EditContent.jsx
  src/components/DashboardEdit/EditContent/EmailListItem/EmailListItem.jsx
  src/components/DashboardEdit/EditContent/MemberListItem/MemberListItem.jsx
  src/components/MyPage/MyPageContent/UpdateProfile.jsx
  src/components/common/Modal/CreateColumnModal/CreateColumnModal.jsx
  src/components/common/Modal/CreateDashboardModal/CreateDashboardModal.jsx
  src/components/common/Modal/TodoModal/TodoModal.jsx
  src/components/common/PopupMenu/PopupMenu.jsx
  src/features/axios.js
  src/features/columnsSlice.js
  src/hooks/useDashboardCardGet.jsx
  src/pages/_app.jsx
  src/pages/dashboard/[dashboardId].jsx
  src/pages/signin.jsx
Labels: 버그픽스

#75 🐛 : 태그 색상 고정, 프로필 등 자잘한 버그 픽스
  src/components/Dashboard/TodoCard/UpdateTodo.jsx
  src/components/DashboardEdit/EditContent/MemberListItem/MemberListItem.jsx
  src/components/common/Avatar/Avatar.jsx
  src/components/common/DropdownMenu/DropdownMenu.jsx
  src/components/common/Header/DashboardHeader.jsx
  src/components/common/Modal/CardModal/CardModal.jsx
  src/components/common/PopupMenu/PopupMenu.jsx
  src/components/common/Tag/TagInput.jsx
  src/components/common/Tag/TagItem.jsx
  src/utils/getRandomColorPair.js
Labels: 버그픽스

#79 Feat:할 일 카드 모달 댓글 무한스크롤 기능 추가 Style: 새로운 대시보드 추가 모달 모바일 폭 고정
  src/components/common/Modal/CardModal/CardModal.jsx
  src/components/common/Modal/CreateDashboardModal/CreateDashboardModal.jsx
  src/components/common/Modal/Modal.jsx
Labels: 모달

#80 ✨Feat : 관리 페이지 완성
  src/components/Dashboard/DashboardCard/DashboardCard.jsx
  src/components/Dashboard/DashboardCardList/DashboardCardList.jsx
  src/components/Dashboard/DashboardHeaderButton/DashboardHeaderButton.jsx
  src/components/Dashboard/TodoCard/UpdateTodo.jsx
  src/components/DashboardEdit/EditContent/DashboardEditPanel.jsx
  src/components/DashboardEdit/EditContent/EditContent.jsx
  src/components/DashboardEdit/EditContent/EmailListItem/EmailListItem.jsx
  src/components/DashboardEdit/EditContent/InvitedEmailList.jsx
  src/components/DashboardEdit/EditContent/MemberListItem/MemberListItem.jsx
  src/components/common/Header/DashboardHeader.jsx
  src/components/common/Modal/CardModal/CardModal.jsx
  src/components/common/Modal/InviteDashboardModal/InviteDashboardModal.jsx
  src/components/common/PopupMenu/PopupMenu.jsx
  src/features/axios.js
  src/features/columnsSlice.js
  src/features/dashboardInfoSlice.js
  src/features/dashboardListSlice.js
  src/features/invitedEmailListSlice.js
  src/features/sidebarDashboardListSlice.js
  src/features/store.js
  src/hooks/useDashboardInfo.jsx
  src/hooks/useDashboardUtilityFunctions.jsx
  src/hooks/useRedirectWithAccessToken.jsx
  src/pages/dashboard/[dashboardId].jsx
  src/pages/dashboard/[dashboardId]/edit.jsx
  src/pages/mydashboard.jsx
  src/pages/mypage.jsx
  src/pages/signin.jsx
  src/pages/signup.jsx
Labels: 대시보드 수정

#83 버그 픽스 완료
  package-lock.json
  package.json
  src/components/Dashboard/DashboardCard/DashboardCard.jsx
  src/components/Dashboard/TodoCard/CreateTodo.jsx
  src/components/DashboardEdit/EditContent/MemberListEdit.jsx
  src/components/DashboardEdit/EditContent/MemberListItem/MemberListItem.jsx
  src/components/MyPage/MyPageContent/MyPageContent.jsx
  src/components/MyPage/MyPageContent/UpdateProfile.jsx
  src/components/MydashboardPage/InvitedDashboard/InvitedDashboard.jsx
  src/components/common/Avatar/Avatar.jsx
  src/components/common/Avatar/AvatarGroup.jsx
  src/components/common/CustomDatePicker/CustomDatePicker.jsx
  src/components/common/CustomDatePicker/CustomInput.jsx
  src/components/common/DropdownMenu/DropdownMenu.jsx
  src/components/common/Header/DashboardHeader.jsx
  src/components/common/Modal/CardModal/CardModal.jsx
  src/components/common/Modal/InviteDashboardModal/InviteDashboardModal.jsx
  src/components/common/Modal/TodoModal/TodoModal.jsx
  src/components/common/PopupMenu/PopupMenu.jsx
  src/components/common/SelectMenu/SelectMenu.jsx
  src/components/common/StatusTag/StatusTag.jsx
  src/components/common/Tag/TagInput.jsx
  src/constants/colors.js
  src/pages/dashboard/[dashboardId]/edit.jsx
  src/pages/test.jsx
  src/utils/getRandomColor.js
Labels: 버그픽스

#84 🐛 fix : 버그 수정 및 카드 제목도 flex-wrap 추가
  src/components/Dashboard/DashboardCard/DashboardCard.jsx
  src/components/Dashboard/DashboardHeaderButton/DashboardHeaderButton.jsx
  src/components/MyPage/MyPageContent/UpdateProfile.jsx
  src/components/common/CustomDatePicker/CustomDatePicker.jsx
  src/components/common/CustomDatePicker/CustomInput.jsx
  src/features/columnsSlice.js
  src/features/invitedEmailListSlice.js
  src/features/userInfoSlice.js
  src/pages/dashboard/[dashboardId].jsx
Labels: 버그픽스

#86 README 작성완료
  README.md
Labels: 문서/파일관리

#87 🐛 : css 버그 수정
  src/components/Dashboard/DashboardCard/DashboardCard.jsx
  src/components/DashboardEdit/EditContent/MemberListEdit.jsx
  src/components/DashboardEdit/EditContent/MemberListItem/MemberListItem.jsx
  src/components/MyPage/MyPageContent/UpdateProfile.jsx
  src/components/common/Avatar/Avatar.jsx
  src/components/common/Avatar/AvatarGroup.jsx
  src/components/common/Header/DashboardHeader.jsx
  src/components/common/Modal/CardModal/CardModal.jsx
  src/components/common/Modal/TodoModal/TodoModal.jsx
  src/components/common/SelectMenu/SelectMenu.jsx
  src/utils/getRandomColor.js
Labels: 버그픽스
